version: '3'

services:
  zookeeper:
    image: 'wurstmeister/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: 'wurstmeister/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_USER: seu_user
      POSTGRES_DB: nome_do_db
    ports:
      - "5432:5432"
    volumes:
      - /home/ubuntu/postgres_data:/var/lib/postgresql/data
